### ISSUE TITLE
能否打包成docker

### ISSUE THREAD

**Issue by Ithrael** [HuoCorp/TerraformGoat#65]
把terraform init这种费时操作打包到docker里，这样我在使用的使用把docker image拉下来后，就不需要在本地terraform init了。terraform在workflow里真的很快。比如这样
https://github.com/Ithrael/terraformk8s/blob/master/Dockerfile#L23

**Comment by teamssix** [comment]
感谢反馈，后面会加入这种方法，确实会比现在的方法在使用体验上要好不少 :+1:
