### ISSUE TITLE
关于aliyun的可用区

### ISSUE THREAD

**Issue by Ithrael** [HuoCorp/TerraformGoat#69]
我比较常用aliyun，注意到我们使用的可用区基本都是cn-beijing-b，一般来说都是买新不买旧嘛。可用区按照英文字母越新越好，机器的架构更新，价格更低。比如我用ssrf这个tf，创建了一个服务器，是ecs.n1.tiny规格的，1C1G，价格是0.15元/时。如果我选择cn-beijing-K，那么同样1C1G，我可以选ecs.s6-c1m1.small规格的，价格是0.115元/时。所以建议能把可用区换掉，这样可以省钱。其他几个云我没咋用，就不清楚了

**Comment by Ithrael** [comment]
@teamssix

**Comment by teamssix** [comment]
有道理，我给改改 👍
